// apps/react-web/src/views/WordBook/index.tsx
import { useState, useEffect } from "react"
import { Button, Checkbox, Input, Pagination, Tag } from "antd"
import { ReadOutlined, PlayCircleOutlined } from "@ant-design/icons"
import { getWordBookList } from "@/apis/word-book"
import type { WordQuery, WordList } from "@en/common/word"
import { useAudio } from "@/hooks/useAudio"

export function WordBook() {
  const [list, setList] = useState<WordList["list"]>([])
  const [total, setTotal] = useState(0)
  const [query, setQuery] = useState<WordQuery>({
    page: 1, pageSize: 12,
    word: "", gk: false, zk: false, gre: false,
    toefl: false, ielts: false, cet6: false, cet4: false, ky: false,
  })
  const { playAudio } = useAudio()

  const getList = async (q: WordQuery) => {
    const res = await getWordBookList(q)
    if (res.success) { setList(res.data.list); setTotal(res.data.total) }
  }

  useEffect(() => { getList(query) }, [])

  const searchWord = () => { const nq = { ...query, page: 1 }; setQuery(nq); getList(nq) }
  const toggleCheck = (key: keyof WordQuery) => setQuery((prev) => ({ ...prev, [key]: !prev[key] }))

  const tags = [{ k: "gk", l: "高考" }, { k: "zk", l: "中考" }, { k: "gre", l: "GRE" }, { k: "toefl", l: "TOEFL" }, { k: "ielts", l: "IELTS" }, { k: "cet6", l: "六级" }, { k: "cet4", l: "四级" }, { k: "ky", l: "考研" }] as const

  return (
    <div className="max-w-6xl mx-auto mt-10 rounded-2xl p-10 bg-gray-50 border border-gray-200">
      <div className="mb-6">
        <ReadOutlined className="text-xl text-blue-600" />
        <span className="text-2xl font-bold text-gray-800">词库列表</span>
      </div>
      <div className="flex items-center flex-wrap gap-2 mb-8">
        <Input className="w-48" placeholder="请输入单词" value={query.word} onChange={e => setQuery(p => ({...p, word: e.target.value}))} onPressEnter={searchWord} />
        {tags.map(({k, l}) => (<Checkbox key={k} checked={!!query[k]} onChange={() => toggleCheck(k)}>{l}</Checkbox>))}
        <Button type="primary" onClick={searchWord}>搜索</Button>
      </div>
      <div className="grid grid-cols-3 gap-3">
        {list.map(item => (
          <div key={item.id} className="bg-white rounded-lg border p-4 hover:shadow-md">
            <div className="text-sm font-semibold text-blue-600 mb-1">{item.word}</div>
            <div className="text-sm text-gray-400 mb-1 flex items-center gap-2">{item.phonetic}<PlayCircleOutlined onClick={() => playAudio(item.word)} className="cursor-pointer" /></div>
            <div className="text-sm text-gray-600 mb-1 line-clamp-2">{item.definition}</div>
            <div className="text-sm text-gray-400 mb-1 line-clamp-2" dangerouslySetInnerHTML={{__html: item.translation||""}} />
            <div className="flex gap-1 flex-wrap mt-3">{tags.map(({k, l}) => (item as any)[k] && <Tag key={k} color="blue">{l}</Tag>)}</div>
          </div>
        ))}
      </div>
      {total > query.pageSize && <Pagination className="mt-10" current={query.page} pageSize={query.pageSize} total={total} onChange={(page, size) => { const nq = {...query, page, pageSize: size}; setQuery(nq); getList(nq) }} />}
    </div>
  )
}

// apps/web/src/views/WordBook/index.vue
<template>
  <div
    class="w-[1200px] mx-auto mt-10 bg-linear-to-br from-blue-50 to-indigo-50 rounded-[20px] p-20 shadow-lg"
  >
    <div class="h-20">
      <div class="flex items-center gap-2">
        <el-icon color="#2563EB" size="20">
          <Reading />
        </el-icon>
        <span class="text-2xl font-bold text-gray-800">词库列表</span>
      </div>
      <div class="text-sm text-gray-600">
        词典来源：牛津、柯林斯、BNC、FRQ、高考、中考、GRE、TOEFL、IELTS、大学英语六级、大学英语四级、考研
      </div>
    </div>
    <div class="flex items-center mb-10">
      <el-input
        @keyup.enter="searchWord"
        class="mr-10"
        v-model="query.word"
        placeholder="请输入单词"
      ></el-input>
      <el-checkbox v-model="query.gk">高考</el-checkbox>
      <el-checkbox v-model="query.zk">中考</el-checkbox>
      <el-checkbox v-model="query.gre">GRE</el-checkbox>
      <el-checkbox v-model="query.toefl">TOEFL</el-checkbox>
      <el-checkbox v-model="query.ielts">IELTS</el-checkbox>
      <el-checkbox v-model="query.cet6">六级</el-checkbox>
      <el-checkbox v-model="query.cet4">四级</el-checkbox>
      <el-checkbox v-model="query.ky">考研</el-checkbox>
      <el-button @click="searchWord" class="ml-10" type="primary">搜索</el-button>
    </div>
    <div class="grid grid-cols-3 gap-2">
      <div
        class="bg-white hover:bg-blue-50 border border-blue-200 text-gray-800 rounded-[10px] p-4 cursor-pointer transition-all duration-200 shadow-sm hover:shadow-md h-[220px]"
        v-for="item in list"
        :key="item.id"
      >
        <div class="">
          <div class="text-sm font-semibold text-blue-600 mb-1">{{ item.word }}</div>
          <div class="text-sm text-gray-500 mb-1 flex items-center gap-2">
            {{ item.phonetic }}
            <el-icon size="18" color="#2563EB" @click="playAudio(item.word+item.definition)">
              <VideoPlay />
            </el-icon>
          </div>
          <div  class="text-sm text-gray-700 mb-1 overflow-hidden line-clamp-2">
            {{ item.definition }}
          </div>
          <div
            v-html="item.translation"
            class="text-sm text-gray-600 mb-1 overflow-hidden line-clamp-2"
          ></div>
          <div class="text-sm text-gray-600 mt-3 flex items-center gap-2 flex-wrap">
            <el-tag v-if="item.gk" type="primary" size="small">高考</el-tag>
            <el-tag v-if="item.zk" type="primary" size="small">中考</el-tag>
            <el-tag v-if="item.gre" type="primary" size="small">GRE</el-tag>
            <el-tag v-if="item.toefl" type="primary" size="small">TOEFL</el-tag>
            <el-tag v-if="item.ielts" type="primary" size="small">IELTS</el-tag>
            <el-tag v-if="item.cet6" type="primary" size="small">六级</el-tag>
            <el-tag v-if="item.cet4" type="primary" size="small">四级</el-tag>
            <el-tag v-if="item.ky" type="primary" size="small">考研</el-tag>
          </div>
        </div>
      </div>
      <el-pagination
        class="mt-10"
        background
        v-model:current-page="query.page"
        v-model:page-size="query.pageSize"
        :total="total"
        @current-change="getList"
        @size-change="getList"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { getWordBookList } from '@/apis/word-book'
import type { WordQuery, WordList } from '@en/common/word'
import { Reading, VideoPlay } from '@element-plus/icons-vue'
import { useAudio } from '@/hooks/useAudio'
const { playAudio } = useAudio({})
const total = ref<WordList['total']>(0)
const list = ref<WordList['list']>([])

const query = ref<WordQuery>({
  page: 1,
  pageSize: 12,
  word: '',
  gk: false,
  zk: false,
  gre: false,
  toefl: false,
  ielts: false,
  cet6: false,
  cet4: false,
  ky: false,
})
const searchWord = () => {
  query.value.page = 1 //重置一下页数
  getList() //重新获取列表
}

const getList = async () => {
  const res = await getWordBookList(query.value)
  if (res.success) {
    total.value = res.data.total
    list.value = res.data.list
  }
}

onMounted(() => {
  getList()
})
</script>
