// apps/react-web/src/views/Chat/components/Bubble.tsx
import { useState, useRef, useEffect } from 'react'
import { Input, Switch } from 'antd'
import {
  AudioOutlined,
  UserOutlined,
  RobotOutlined,
  DashboardOutlined,
  MessageOutlined,
} from '@ant-design/icons'
import { marked } from 'marked'
import type { ChatMessageList } from '@en/common/chat'

interface Props {
  list: ChatMessageList
  onSendMessage: (message: string, deepThink: boolean, webSearch: boolean) => void
}

export default function Bubble({ list, onSendMessage }: Props) {
  const [message, setMessage] = useState('')
  const [deepThink, setDeepThink] = useState(false)
  const [webSearch, setWebSearch] = useState(false)
  const [isRecording, setIsRecording] = useState(false)
  const scrollRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (scrollRef.current) scrollRef.current.scrollTop = scrollRef.current.scrollHeight
  }, [list])

  const startVoice = () => {
    if (!('webkitSpeechRecognition' in window) && !('SpeechRecognition' in window)) return
    const SR = (window as any).webkitSpeechRecognition || (window as any).SpeechRecognition
    const rec = new SR()
    rec.lang = 'en-US'
    rec.interimResults = false
    rec.continuous = false
    setIsRecording(true)
    rec.onresult = (e: any) => {
      setMessage(p => p + ' ' + e.results[0][0].transcript)
      setIsRecording(false)
    }
    rec.onerror = () => setIsRecording(false)
    rec.onend = () => setIsRecording(false)
    rec.start()
  }

  const handleSend = () => {
    const t = message.trim()
    if (!t) return
    onSendMessage(t, deepThink, webSearch)
    setMessage('')
  }
  const parseMarkdown = (text: string) => marked(text) as string

  return (
    <div className='flex-1 flex flex-col min-h-0 bg-gray-50'>
      <div ref={scrollRef} className='flex-1 overflow-y-auto px-6 py-4'>
        {!list?.length ? (
          <div className='flex flex-col items-center justify-center h-full text-center'>
            <div className='w-16 h-16 bg-blue-100 rounded-2xl flex items-center justify-center mb-4'>
              <MessageOutlined />
            </div>
            <h3 className='text-base font-semibold text-gray-800 mb-1'>开始你的英语学习之旅</h3>
            <p className='text-sm text-gray-400 max-w-xs'>
              选择左侧对话模式，然后用英语或中文与 AI 交流
            </p>
          </div>
        ) : (
          list.map((item, i) => (
            <div key={i} className='mb-6'>
              {item.role === 'human' ? (
                <div className='flex justify-end gap-3'>
                  <div className='max-w-[75%] bg-blue-600 text-white rounded-2xl rounded-br-md px-4 py-2.5 text-sm shadow-sm'>
                    {item.content}
                  </div>
                  <div className='w-9 h-9 rounded-full bg-blue-100 flex items-center justify-center shrink-0'>
                    <UserOutlined className='text-blue-600' />
                  </div>
                </div>
              ) : (
                <div className='flex gap-3'>
                  <div className='w-9 h-9 rounded-full bg-blue-600 flex items-center justify-center shrink-0'>
                    <RobotOutlined className='text-white' />
                  </div>
                  <div className='max-w-[75%] min-w-0'>
                    {item.reasoning && (
                      <details className='mb-2 group'>
                        <summary className='flex items-center gap-1.5 text-xs text-gray-400 cursor-pointer hover:text-gray-500'>
                          <DashboardOutlined /> 深度思考
                        </summary>
                        <div
                          className='mt-2 p-3 rounded-lg bg-gray-50 border text-xs text-gray-500 whitespace-pre-wrap'
                          dangerouslySetInnerHTML={{ __html: parseMarkdown(item.reasoning) }}
                        />
                      </details>
                    )}
                    {item.content && (
                      <div
                        className='text-sm text-gray-700 bg-white rounded-2xl rounded-bl-md px-4 py-2.5 shadow-sm'
                        dangerouslySetInnerHTML={{ __html: parseMarkdown(item.content) }}
                      />
                    )}
                    {item.role === 'ai' && !item.content && !item.reasoning && (
                      <div className='flex items-center gap-1 text-gray-400 text-sm'>
                        <span>思考中</span>
                        <span className='animate-pulse'>...</span>
                      </div>
                    )}
                  </div>
                </div>
              )}
            </div>
          ))
        )}
      </div>
      <div className='border-t border-gray-200 bg-white p-4'>
        <div className='flex items-center gap-2 mb-2'>
          <span className='text-xs text-gray-400'>深度思考</span>
          <Switch size='small' checked={deepThink} onChange={setDeepThink} />
          <span className='text-xs text-gray-400 ml-4'>联网搜索</span>
          <Switch size='small' checked={webSearch} onChange={setWebSearch} />
        </div>
        <div className='flex items-center gap-2'>
          <Input.TextArea
            value={message}
            onChange={e => setMessage(e.target.value)}
            onPressEnter={e => {
              if (!e.shiftKey) {
                e.preventDefault()
                message.trim() && handleSend()
              }
            }}
            placeholder='用英语或中文与 AI 交流...'
            autoSize={{ minRows: 1, maxRows: 4 }}
            className='flex-1'
          />
          {!isRecording ? (
            <button
              type='button'
              className='p-2 text-gray-400 hover:text-blue-500'
              onClick={startVoice}
              title='语音输入'
            >
              <AudioOutlined className='text-lg' />
            </button>
          ) : (
            <span className='text-red-500 animate-pulse text-sm'>录音中...</span>
          )}
        </div>
      </div>
    </div>
  )
}

// apps/web/src/views/Chat/components/Bubble.vue
<template>
  <div class="flex-1 flex flex-col min-h-0 bg-surface">
    <!-- 消息列表 -->
    <div class="flex-1 overflow-y-auto px-6 py-4" ref="scrollContainer">
      <!-- 空状态 -->
      <div
        v-if="!list?.length"
        class="flex flex-col items-center justify-center h-full text-center"
      >
        <div class="w-16 h-16 bg-primary-100 rounded-2xl flex items-center justify-center mb-4">
          <el-icon :size="32" color="var(--color-primary-500)"><ChatDotRound /></el-icon>
        </div>
        <h3 class="text-base font-semibold text-text-primary mb-1">开始你的英语学习之旅</h3>
        <p class="text-sm text-text-tertiary max-w-xs">
          选择左侧对话模式，然后用英语或中文与 AI 交流
        </p>
      </div>

      <!-- 消息 -->
      <template v-else>
        <div v-for="(item, index) in list" :key="index" class="mb-6">
          <!-- 用户消息 -->
          <div v-if="item.role === 'human'" class="flex justify-end gap-3">
            <div
              class="max-w-[75%] bg-primary-600 text-white rounded-2xl rounded-br-md px-4 py-2.5 text-sm leading-relaxed shadow-sm"
            >
              {{ item.content }}
            </div>
            <div
              class="w-9 h-9 rounded-full bg-primary-100 flex items-center justify-center shrink-0"
            >
              <el-icon :size="18" color="var(--color-primary-600)"><User /></el-icon>
            </div>
          </div>

          <!-- AI 消息 -->
          <div v-else class="flex gap-3">
            <div
              class="w-9 h-9 rounded-full bg-primary-600 flex items-center justify-center shrink-0"
            >
              <el-icon :size="18" color="white"><Cpu /></el-icon>
            </div>
            <div class="max-w-[75%] min-w-0">
              <!-- 深度思考折叠区 -->
              <details v-if="item.reasoning" class="mb-2 group" :open="false">
                <summary
                  class="flex items-center gap-1.5 text-xs text-text-tertiary cursor-pointer hover:text-text-secondary transition-colors select-none"
                >
                  <el-icon :size="14"><DataBoard /></el-icon>
                  <span>深度思考</span>
                  <el-icon :size="12" class="transition-transform group-open:rotate-90"
                    ><ArrowRight
                  /></el-icon>
                </summary>
                <div
                  class="mt-2 px-3 py-2 bg-primary-50/50 rounded-lg text-xs text-text-secondary leading-relaxed border border-primary-100/50 whitespace-pre-wrap"
                >
                  {{ item.reasoning }}
                </div>
              </details>

              <!-- AI 回复 -->
              <div
                v-if="item.content !== ''"
                class="bg-white rounded-2xl rounded-bl-md px-4 py-2.5 text-sm text-text-primary leading-relaxed shadow-sm border border-border deepseek-markdown"
                v-html="parseMarkdown(item.content)"
              />

              <!-- 流式生成中的省略号 -->
              <div
                v-if="item.role === 'ai' && item.content === '' && !item.reasoning"
                class="bg-white rounded-2xl rounded-bl-md px-4 py-3 text-sm text-text-tertiary shadow-sm border border-border inline-flex items-center gap-1"
              >
                <span
                  class="w-1.5 h-1.5 bg-primary-400 rounded-full animate-bounce"
                  style="animation-delay: 0ms"
                ></span>
                <span
                  class="w-1.5 h-1.5 bg-primary-400 rounded-full animate-bounce"
                  style="animation-delay: 150ms"
                ></span>
                <span
                  class="w-1.5 h-1.5 bg-primary-400 rounded-full animate-bounce"
                  style="animation-delay: 300ms"
                ></span>
              </div>
            </div>
          </div>
        </div>
      </template>
      <div ref="chatRef"></div>
    </div>

    <!-- 输入区 -->
    <div class="border-t border-border bg-white px-5 py-4">
      <!-- 功能开关 -->
      <div class="flex items-center gap-2 mb-3">
        <button
          @click="deepThink = !deepThink"
          :class="[
            'inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors cursor-pointer border',
            deepThink
              ? 'bg-primary-50 border-primary-200 text-primary-700'
              : 'bg-white border-border text-text-tertiary hover:bg-surface',
          ]"
        >
          <el-icon :size="14"><DataBoard /></el-icon>
          深度思考
        </button>
        <button
          @click="webSearch = !webSearch"
          :class="[
            'inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors cursor-pointer border',
            webSearch
              ? 'bg-primary-50 border-primary-200 text-primary-700'
              : 'bg-white border-border text-text-tertiary hover:bg-surface',
          ]"
        >
          <el-icon :size="14"><Connection /></el-icon>
          联网搜索
        </button>
      </div>

      <!-- 输入框 + 按钮 -->
      <div class="flex items-end gap-2">
        <el-input
          @keyup.enter="sendMessage"
          type="textarea"
          :rows="2"
          v-model="message"
          placeholder="用英语或中文开始对话..."
          class="flex-1"
        />
        <button
          @click="sendMessage"
          :disabled="!message.trim()"
          class="btn-primary w-10 h-10 p-0! rounded-xl! shrink-0"
          aria-label="发送消息"
        >
          <el-icon :size="18"><Promotion /></el-icon>
        </button>
        <button
          v-if="!isRecording"
          @click="startRecording"
          class="btn-ghost w-10 h-10 p-0! rounded-xl! shrink-0 border border-border"
          aria-label="语音输入"
        >
          <el-icon :size="18"><Microphone /></el-icon>
        </button>
        <button
          v-else
          @click="stopRecording"
          class="btn-danger w-10 h-10 p-0! rounded-xl! shrink-0 border border-red-200"
          aria-label="停止录音"
        >
          <el-icon :size="18"><VideoPause /></el-icon>
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
  import { ref, useTemplateRef, watch, nextTick } from 'vue'
  import {
    Promotion,
    Microphone,
    VideoPause,
    ChatDotRound,
    User,
    Cpu,
    DataBoard,
    Connection,
    ArrowRight,
  } from '@element-plus/icons-vue'
  import type { ChatMessageList } from '@en/common/chat'
  import { marked } from 'marked'
  import '@/assets/css/deep-seek.css'
  import { useVoiceToText } from '@/hooks/useVoiceToText'

  const { isRecording, start, stop } = useVoiceToText({
    lang: 'zh-CN',
    continuous: true,
  })

  const deepThink = ref(false)
  const webSearch = ref(false)
  const emits = defineEmits(['onSendMessage'])
  const chatRef = useTemplateRef<HTMLDivElement>('chatRef')
  const props = defineProps<{
    list?: ChatMessageList
  }>()
  const message = ref<string>('')

  const sendMessage = () => {
    if (!message.value.trim()) return
    emits('onSendMessage', message.value, deepThink.value, webSearch.value)
    message.value = ''
  }

  const parseMarkdown = (content: string) => {
    if (!content) return ''
    return marked.parse(content)
  }

  const startRecording = () => {
    start(result => {
      message.value = result
    })
  }

  const stopRecording = () => {
    stop()
    sendMessage()
  }

  watch(
    () => props.list,
    () => {
      nextTick(() => {
        chatRef.value?.scrollIntoView({ behavior: 'smooth' })
      })
    },
    { immediate: true, deep: true }
  )
</script>
