// apps/react-web/src/views/Chat/components/Conversations.tsx
import { useState, useEffect } from 'react'
import { getChatMode } from '@/apis/chat'
import type { ChatModeList, ChatMode, ChatRoleType } from '@en/common/chat'
import {
  CommentOutlined,
  EditOutlined,
  FileTextOutlined,
  AudioOutlined,
  MessageOutlined,
} from '@ant-design/icons'

const modeIconMap: Record<string, React.ReactNode> = {
  语法: <EditOutlined />,
  写作: <FileTextOutlined />,
  面试: <AudioOutlined />,
  对话: <CommentOutlined />,
}

interface Props {
  onGetRole: (role: ChatRoleType) => void
}

export default function Conversations({ onGetRole }: Props) {
  const [chatMode, setChatMode] = useState<ChatModeList>([])
  const [active, setActive] = useState<string | null>(null)

  const getChatModeList = async () => {
    const res = await getChatMode()
    setChatMode(res.data)
    const firstId = res.data[0]?.id ?? null
    setActive(firstId)
    if (res.data[0]?.role) onGetRole(res.data[0].role)
  }

  useEffect(() => {
    getChatModeList()
  }, [])

  const changeActive = (mode: ChatMode) => {
    setActive(mode.id)
    onGetRole(mode.role)
  }

  const getIcon = (label: string) => {
    for (const key of Object.keys(modeIconMap)) {
      if (label.includes(key)) return modeIconMap[key]
    }
    return <MessageOutlined />
  }

  return (
    <aside className='w-[260px] shrink-0 border-r border-gray-200 bg-white flex flex-col'>
      <div className='px-5 pt-5 pb-3'>
        <h2 className='text-sm font-semibold text-gray-800'>对话模式</h2>
        <p className='text-xs text-gray-400 mt-1'>选择适合你的 AI 角色</p>
      </div>
      <nav className='flex-1 px-3 pb-3 space-y-1 overflow-y-auto'>
        {chatMode.map(mode => (
          <button
            key={mode.id}
            onClick={() => changeActive(mode)}
            className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-left transition-colors duration-150 cursor-pointer ${
              active === mode.id
                ? 'bg-blue-50 text-blue-700 font-medium'
                : 'text-gray-500 hover:bg-gray-50'
            }`}
          >
            <span className='text-lg'>{getIcon(mode.label)}</span>
            <span className='text-sm'>{mode.label}</span>
          </button>
        ))}
      </nav>
    </aside>
  )
}

// apps/web/src/views/Chat/components/Conversations.vue
<template>
  <div
    class="p-5 rounded-[5px] w-[256px] bg-purple-50 border border-right-1 border-t-0 border-b-0 border-l-0 border-gray-200"
  >
    <div
      @click="changeActive(value)"
      :class="{ 'bg-purple-300': active === value.id }"
      class="rounded-[5px] p-2 transition-all duration-300"
      v-for="value in chatMode"
      :key="value.id"
    >
      <div class="text-sm cursor-pointer p-2 px-4 text-gray-700">
        {{ value.label }}
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
  import { ref, onMounted } from 'vue'
  import type { ChatModeList, ChatMode } from '@en/common/chat'
  import { getChatMode } from '@/apis/chat'
  const emits = defineEmits(['onGetRole'])
  const chatMode = ref<ChatModeList>([]) //消息模式列表
  const active = ref<string | null>(null) //当前激活的id
  //切换消息模式
  const changeActive = (value: ChatMode) => {
    active.value = value.id
    emits('onGetRole', value.role) //派发role
  }
  //获取消息模式列表
  const getChatModeList = async () => {
    const res = await getChatMode()
    chatMode.value = res.data
    active.value = res.data[0]?.id ?? null //默认选中第一个
    emits('onGetRole', res.data[0]?.role) //派发role
  }
  onMounted(() => {
    getChatModeList()
  })
</script>
