// apps/react-web/web/src/views/Chat/components/Conversations.vue
<template>
  <aside class="w-[260px] shrink-0 border-r border-border bg-white flex flex-col">
    <!-- 标题 -->
    <div class="px-5 pt-5 pb-3">
      <h2 class="text-sm font-semibold text-text-primary">对话模式</h2>
      <p class="text-xs text-text-tertiary mt-1">选择适合你的 AI 角色</p>
    </div>

    <!-- 模式列表 -->
    <nav class="flex-1 px-3 pb-3 space-y-1 overflow-y-auto">
      <button
        v-for="mode in chatMode"
        :key="mode.id"
        @click="changeActive(mode)"
        :class="[
          'w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-left transition-colors duration-150 cursor-pointer',
          active === mode.id
            ? 'bg-primary-50 text-primary-700 font-medium'
            : 'text-text-secondary hover:bg-surface',
        ]"
      >
        <el-icon :size="18"><component :is="modeIcon(mode.label)" /></el-icon>
        <span class="text-sm">{{ mode.label }}</span>
      </button>
    </nav>
  </aside>
</template>

<script setup lang="ts">
  import { ref, onMounted } from 'vue'
  import type { ChatModeList, ChatMode } from '@en/common/chat'
  import { getChatMode } from '@/apis/chat'
  import {
    ChatDotRound,
    EditPen,
    Document,
    Microphone,
    ChatLineSquare,
  } from '@element-plus/icons-vue'

  const emits = defineEmits(['onGetRole'])
  const chatMode = ref<ChatModeList>([])
  const active = ref<string | null>(null)

  // 根据模式标签匹配图标
  const modeIcon = (label: string) => {
    const map: Record<string, any> = {
      语法: EditPen,
      写作: Document,
      面试: Microphone,
      对话: ChatDotRound,
    }
    for (const key of Object.keys(map)) {
      if (label.includes(key)) return map[key]
    }
    return ChatLineSquare
  }

  const changeActive = (value: ChatMode) => {
    active.value = value.id
    emits('onGetRole', value.role)
  }

  const getChatModeList = async () => {
    const res = await getChatMode()
    chatMode.value = res.data
    active.value = res.data[0]?.id ?? null
    emits('onGetRole', res.data[0]?.role)
  }

  onMounted(() => getChatModeList())
</script>

// apps/react-web/src/views/Chat/components/Conversations.tsx
import { useState, useEffect } from 'react'
import { getChatMode } from '@/apis/chat'
import type { ChatModeList, ChatMode, ChatRoleType } from '@en/common/chat'
import {
  CommentOutlined,
  EditOutlined,
  FileTextOutlined,
  AudioOutlined,
  MessageOutlined,
} from '@ant-design/icons'

const modeIconMap: Record<string, React.ReactNode> = {
  语法: <EditOutlined />,
  写作: <FileTextOutlined />,
  面试: <AudioOutlined />,
  对话: <CommentOutlined />,
}

interface Props {
  onGetRole: (role: ChatRoleType) => void
}

export default function Conversations({ onGetRole }: Props) {
  const [chatMode, setChatMode] = useState<ChatModeList>([])
  const [active, setActive] = useState<string | null>(null)

  const getChatModeList = async () => {
    const res = await getChatMode()
    setChatMode(res.data)
    const firstId = res.data[0]?.id ?? null
    setActive(firstId)
    if (res.data[0]?.role) onGetRole(res.data[0].role)
  }

  useEffect(() => {
    getChatModeList()
  }, [])

  const changeActive = (mode: ChatMode) => {
    setActive(mode.id)
    onGetRole(mode.role)
  }

  const getIcon = (label: string) => {
    for (const key of Object.keys(modeIconMap)) {
      if (label.includes(key)) return modeIconMap[key]
    }
    return <MessageOutlined />
  }

  return (
    <aside className='w-[260px] shrink-0 border-r border-gray-200 bg-white flex flex-col'>
      <div className='px-5 pt-5 pb-3'>
        <h2 className='text-sm font-semibold text-gray-800'>对话模式</h2>
        <p className='text-xs text-gray-400 mt-1'>选择适合你的 AI 角色</p>
      </div>
      <nav className='flex-1 px-3 pb-3 space-y-1 overflow-y-auto'>
        {chatMode.map(mode => (
          <button
            key={mode.id}
            onClick={() => changeActive(mode)}
            className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-left transition-colors duration-150 cursor-pointer ${
              active === mode.id
                ? 'bg-blue-50 text-blue-700 font-medium'
                : 'text-gray-500 hover:bg-gray-50'
            }`}
          >
            <span className='text-lg'>{getIcon(mode.label)}</span>
            <span className='text-sm'>{mode.label}</span>
          </button>
        ))}
      </nav>
    </aside>
  )
}
