// apps/web/src/components/Login/LoginForm.vue
<template>
  <div class="mb-8">
    <h1 class="section-title">登录 English App</h1>
    <p class="section-desc">继续你的英语学习之旅</p>
  </div>

  <el-form ref="formRef" :model="form" :rules="rules" class="space-y-5">
    <el-form-item prop="phone">
      <el-input
        :maxlength="11"
        v-model="form.phone"
        placeholder="请输入手机号"
        size="large"
        class="h-11"
        :prefix-icon="User"
      />
    </el-form-item>

    <el-form-item prop="password">
      <el-input
        v-model="form.password"
        type="password"
        placeholder="请输入密码"
        size="large"
        class="h-11"
        :prefix-icon="Lock"
        show-password
      />
    </el-form-item>

    <el-form-item class="pt-4">
      <el-button
        type="primary"
        size="large"
        class="w-full h-11 text-base font-semibold"
        @click="handleLogin"
      >
        登录
      </el-button>
    </el-form-item>
  </el-form>
</template>

<script setup lang="ts">
  import { ref, useTemplateRef, toRaw } from 'vue'
  import { User, Lock } from '@element-plus/icons-vue'
  import { login } from '@/apis/user' //登录的接口
  import type { UserLogin } from '@en/common/user' //登录类型
  import md5 from 'md5' //md5加密
  import type { FormInstance } from 'element-plus'
  import { ElMessage } from 'element-plus'
  import { useUserStore } from '@/stores/user'
  import { useLogin } from '@/hooks/useLogin'
  const { hide } = useLogin()
  const formRef = useTemplateRef<FormInstance>('formRef')
  const userStore = useUserStore()
  const form = ref<UserLogin>({
    phone: '',
    password: '',
  })

  const rules = {
    phone: [
      { required: true, message: '请输入手机号', trigger: 'blur' },
      { pattern: /^1[3-9]\d{9}$/, message: '请输入正确的手机号', trigger: 'blur' },
    ],
    password: [
      { required: true, message: '请输入密码', trigger: 'blur' },
      { min: 8, message: '密码长度至少为8位', trigger: 'blur' },
    ],
  }

  const handleLogin = async () => {
    await formRef.value?.validate() //触发校验的
    const res = await login({
      ...toRaw(form.value),
      password: toRaw(md5(form.value.password)),
    })
    if (res.code === 200) {
      userStore.setUser(res.data)
      ElMessage.success('登录成功')
      hide()
    } else {
      ElMessage.error(res.message)
    }
  }
</script>

// apps/react-web/src/components/Login/LoginForm.tsx
import { Form, Input, Button, App } from "antd"
import { UserOutlined, LockOutlined } from "@ant-design/icons"
import md5 from "md5"
import { login } from "@/apis/user"
import { useUserStore } from "@/stores/user"
import { useLoginDialogStore } from "@/stores/loginDialog"

interface LoginFormData {
  phone: string
  password: string
}

export default function LoginForm() {
  const [form] = Form.useForm<LoginFormData>()
  const { hide } = useLoginDialogStore()
  const setUser = useUserStore((s) => s.setUser)
  const { message } = App.useApp()

  const handleFinish = async (values: LoginFormData) => {
    const res = await login({
      phone: values.phone,
      password: md5(values.password),
    })
    if (res.success) {
      setUser(res.data)
      message.success("登录成功")
      hide()
    } else {
      message.error(res.message || "登录失败")
    }
  }

  return (
    <div>
      <div className="mb-8 text-center">
        <h1 className="text-xl font-bold text-gray-800">登录 English App</h1>
        <p className="mt-1 text-sm text-gray-400">继续你的英语学习之旅</p>
      </div>

      <Form form={form} layout="vertical" onFinish={handleFinish} size="large">
        <Form.Item
          name="phone"
          rules={[
            { required: true, message: "请输入手机号" },
            { pattern: /^1[3-9]\d{9}$/, message: "请输入正确的手机号" },
          ]}
        >
          <Input prefix={<UserOutlined />} maxLength={11} placeholder="请输入手机号" />
        </Form.Item>

        <Form.Item
          name="password"
          rules={[
            { required: true, message: "请输入密码" },
            { min: 8, message: "密码长度至少为8位" },
          ]}
        >
          <Input.Password prefix={<LockOutlined />} placeholder="请输入密码" />
        </Form.Item>

        <Form.Item className="pt-4">
          <Button type="primary" htmlType="submit" block size="large" className="font-semibold">
            登录
          </Button>
        </Form.Item>
      </Form>
    </div>
  )
}
