// apps/web/src/components/Login/ModelViewer.vue
<template>
  <div class="relative w-[460px] h-full bg-primary-600">
    <canvas class="w-full h-full" ref="canvasRef"></canvas>
    <div class="absolute top-6 left-6">
      <div class="flex items-center gap-2">
        <div
          class="w-10 h-10 bg-white rounded-lg flex items-center justify-center"
        >
          <span class="text-primary-600 font-bold text-xl">E</span>
        </div>
        <span class="text-white text-lg font-semibold">English App</span>
      </div>
    </div>
    <!-- 登录/注册切换按钮 -->
    <div class="absolute top-6 right-6">
      <div class="flex items-center gap-1 bg-white/15 rounded-lg p-1">
        <button @click="loadModel('login')" :class="loginClass">登录</button>
        <button @click="loadModel('register')" :class="registerClass">注册</button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
  import { ref, computed, onMounted, useTemplateRef } from 'vue'
  import * as THREE from 'three'
  import type { LoginType } from './type'
  import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js' //gltf模型加载器
  import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js' //轨道控制器
  const canvasRef = useTemplateRef<HTMLCanvasElement>('canvasRef') //获取canvas元素引用 渲染容器
  const type = ref<LoginType>('login') // 登录/注册类型
  const loginClass = computed(() => {
    return type.value === 'login'
      ? 'bg-white text-primary-700 px-4 py-2 rounded-md text-sm font-medium transition-colors duration-200'
      : 'text-white/70 hover:text-white hover:bg-white/10 px-4 py-2 rounded-md text-sm font-medium transition-colors duration-200'
  })
  const registerClass = computed(() => {
    return type.value === 'register'
      ? 'bg-white text-primary-700 px-4 py-2 rounded-md text-sm font-medium transition-colors duration-200'
      : 'text-white/70 hover:text-white hover:bg-white/10 px-4 py-2 rounded-md text-sm font-medium transition-colors duration-200'
  })
  const emits = defineEmits(['changeType'])
  const scene = new THREE.Scene() //创建场景
  const clock = new THREE.Timer() //创建时钟
  let currentModel: THREE.Group | null = null //记录当前的模型
  let mixer: THREE.AnimationMixer | null = null //记录当前的动画混合器
  const loadModel = (url: LoginType) => {
    //移除当前模型
    if (currentModel) {
      scene.remove(currentModel)
      currentModel = null
    }
    //加载新模型
    const loader = new GLTFLoader()
    type.value = url
    if (url === 'login') {
      loader.load('/models/login/scene.gltf', gltf => {
        currentModel = gltf.scene
        scene.add(currentModel)
        scene.position.y = -0.8 //往下一点
        currentModel.scale.set(0.8, 0.8, 0.8)
      })
    }
    if (url === 'register') {
      loader.load('/models/register/scene.gltf', gltf => {
        currentModel = gltf.scene
        scene.add(currentModel)
        scene.position.y = -0.8 //往下一点
        currentModel.scale.set(0.8, 0.8, 0.8)
        if (gltf.animations && gltf.animations.length > 0) {
          mixer = new THREE.AnimationMixer(currentModel)
          gltf.animations.forEach(animation => {
            const action = mixer!.clipAction(animation)
            action.play()
          })
        }
      })
    }
    emits('changeType', url) // 通知父组件切换类型
  }

  const initThree = () => {
    const width = canvasRef.value!.clientWidth //获取canvas宽度
    const height = canvasRef.value!.clientHeight //获取canvas高度
    const camera = new THREE.PerspectiveCamera(60, width / height, 0.1, 1000) //创建相机
    camera.position.set(1, 0.5, 1) //设置相机位置
    const renderer = new THREE.WebGLRenderer({
      canvas: canvasRef.value!, //渲染容器
      antialias: true, //抗锯齿
      alpha: true, //透明背景
      precision: 'highp', //高精度
      powerPreference: 'high-performance', //高性能
    })
    loadModel(type.value)
    renderer.setSize(width, height) //设置渲染器大小
    renderer.render(scene, camera) //渲染场景
    const controls = new OrbitControls(camera, renderer.domElement) //创建轨道控制器
    const animate = () => {
      requestAnimationFrame(animate)
      if (mixer) {
        mixer.update(clock.getDelta())
      }
      scene.rotation.y += 0.002 //旋转场景
      controls.update() //更新轨道控制器
      renderer.render(scene, camera) //渲染场景
    }
    animate()
  }

  onMounted(() => {
    initThree()
  })
</script>

// apps/react-web/src/components/Login/ModelViewer.tsx
import { useRef, useEffect } from 'react'
import * as THREE from 'three'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js'
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js'

interface Props {
  modelType?: 'login' | 'register'
  onChangeType?: (type: 'login' | 'register') => void
}

export default function ModelViewer({ modelType = 'login', onChangeType }: Props) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const sceneRef = useRef<THREE.Scene | null>(null)
  const mixerRef = useRef<THREE.AnimationMixer | null>(null)
  const modelRef = useRef<THREE.Group | null>(null)

  const loadModel = (type: string) => {
    const scene = sceneRef.current
    if (!scene) return
    if (modelRef.current) {
      scene.remove(modelRef.current)
      modelRef.current = null
    }
    const loader = new GLTFLoader()
    const path = type === 'login' ? '/models/login/scene.gltf' : '/models/register/scene.gltf'
    loader.load(path, gltf => {
      modelRef.current = gltf.scene
      modelRef.current.scale.set(0.8, 0.8, 0.8)
      scene.add(modelRef.current)
      scene.position.y = -0.8
      if (gltf.animations && gltf.animations.length > 0) {
        mixerRef.current = new THREE.AnimationMixer(modelRef.current)
        gltf.animations.forEach(anim => {
          mixerRef.current!.clipAction(anim).play()
        })
      }
    })
  }

  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas) return
    const width = canvas.clientWidth
    const height = canvas.clientHeight
    const scene = new THREE.Scene()
    sceneRef.current = scene

    const camera = new THREE.PerspectiveCamera(60, width / height, 0.1, 1000)
    camera.position.set(1, 0.5, 1)

    const renderer = new THREE.WebGLRenderer({
      canvas,
      antialias: true,
      alpha: true,
      precision: 'highp',
      powerPreference: 'high-performance',
    })
    renderer.setSize(width, height)

    loadModel(modelType)
    const controls = new OrbitControls(camera, renderer.domElement)
    const clock = new THREE.Clock()

    let animId: number
    const animate = () => {
      animId = requestAnimationFrame(animate)
      const delta = clock.getDelta()
      if (mixerRef.current) mixerRef.current.update(delta)
      scene.rotation.y += 0.002
      controls.update()
      renderer.render(scene, camera)
    }
    animate()

    return () => {
      cancelAnimationFrame(animId)
      renderer.dispose()
      controls.dispose()
      if (modelRef.current) {
        scene.remove(modelRef.current)
      }
    }
  }, [])

  const loginActive = modelType === 'login'
  const registerActive = modelType === 'register'

  return (
    <div className='relative w-[460px] h-full bg-blue-600'>
      <canvas ref={canvasRef} className='w-full h-full' />
      <div className='absolute top-6 left-6'>
        <div className='flex items-center gap-2'>
          <div className='w-10 h-10 bg-white rounded-lg flex items-center justify-center'>
            <span className='text-blue-600 font-bold text-xl'>E</span>
          </div>
          <span className='text-white text-lg font-semibold'>English App</span>
        </div>
      </div>
      <div className='absolute top-6 right-6'>
        <div className='flex items-center gap-1 bg-white/15 rounded-lg p-1'>
          <button
            onClick={() => {
              loadModel('login')
              onChangeType?.('login')
            }}
            className={
              loginActive
                ? 'bg-white text-blue-700 px-4 py-2 rounded-md text-sm font-medium'
                : 'text-white/70 hover:text-white hover:bg-white/10 px-4 py-2 rounded-md text-sm font-medium'
            }
          >
            登录
          </button>
          <button
            onClick={() => {
              loadModel('register')
              onChangeType?.('register')
            }}
            className={
              registerActive
                ? 'bg-white text-blue-700 px-4 py-2 rounded-md text-sm font-medium'
                : 'text-white/70 hover:text-white hover:bg-white/10 px-4 py-2 rounded-md text-sm font-medium'
            }
          >
            注册
          </button>
        </div>
      </div>
    </div>
  )
}
