// apps/react-web/src/views/Course/components/Pay.tsx
import { useState, useEffect } from "react"
import { Modal, App } from "antd"
import dayjs from "dayjs"
import { uploadUrl } from "@/apis"
import { createPay } from "@/apis/pay"
import { useSocket } from "@/hooks/useSocket"
import type { Course } from "@en/common/course"
import type { CreatePayDto } from "@en/common/pay"

interface Props {
  visible: boolean
  course: Course | null
  onClose: () => void
}

export default function PayDialog({ visible, course, onClose }: Props) {
  const [isPay, setIsPay] = useState(false)
  const [timeExpire, setTimeExpire] = useState(0)
  const { getSocket } = useSocket()
  const { message } = App.useApp()

  // Socket 监听支付成功
  useEffect(() => {
    const socket = getSocket()
    if (!socket) return
    socket.on("paymentSuccess", () => {
      if (visible) {
        message.success({ content: "支付成功", duration: 10 })
        onClose()
      }
    })
    return () => { socket.off("paymentSuccess") }
  }, [visible])

  const handleConfirm = async () => {
    if (!course) return
    const body: CreatePayDto = {
      subject: course.name,
      body: course.description || "",
      total_amount: course.price || "",
      courseId: course.id,
    }
    const res = await createPay(body)
    if (res.code === 200) {
      setIsPay(true)
      window.open(res.data.payUrl, "_blank")
      setTimeExpire(res.data.timeExpire)
    } else {
      message.error(res.message || "支付失败")
      setIsPay(false)
    }
  }

  const handleClose = () => {
    setTimeExpire(0)
    setIsPay(false)
    onClose()
  }

  return (
    <Modal open={visible} onCancel={handleClose} footer={null} centered width={480} destroyOnClose>
      <div className="px-2 pt-2 pb-4">
        <h2 className="text-lg font-semibold text-gray-800">确认支付</h2>
        <p className="mt-1 text-sm text-gray-500">请核对课程信息后完成支付</p>

        {course && (
          <div className="space-y-4 mt-4">
            <div className="flex gap-4 rounded-xl bg-gray-50 p-4">
              <div className="w-20 h-20 shrink-0 rounded-lg overflow-hidden">
                <img src={uploadUrl + course.url} alt={course.name} className="w-full h-full object-cover" />
              </div>
              <div className="min-w-0 flex-1">
                <h3 className="text-sm font-medium text-gray-800 line-clamp-2">{course.name}</h3>
                <p className="mt-1 text-xs text-gray-400">讲师 {course.teacher}</p>
              </div>
            </div>
            <div className="flex items-center justify-between rounded-xl border border-gray-200 bg-blue-50 px-4 py-3">
              <span className="text-sm text-gray-500">支付金额</span>
              <span className="text-xl font-bold text-blue-600">¥{course.price}</span>
            </div>
            {timeExpire > 0 && (
              <div className="flex flex-col items-center rounded-xl border border-orange-200 bg-orange-50 px-4 py-3">
                <span className="text-sm text-gray-500">支付剩余时间</span>
                <span className="text-lg font-bold text-orange-600">
                  {dayjs(timeExpire).format("HH:mm:ss")}
                </span>
              </div>
            )}
          </div>
        )}

        <div className="flex gap-3 mt-6">
          <button
            type="button"
            className="flex-1 py-2.5 rounded-xl text-sm font-medium text-gray-500 border border-gray-200 bg-white hover:bg-gray-50 transition-colors cursor-pointer"
            onClick={handleClose}
          >
            取消
          </button>
          <button
            type="button"
            className="flex-1 py-2.5 text-sm bg-blue-600 text-white rounded-xl font-medium cursor-pointer hover:bg-blue-700 disabled:opacity-50"
            disabled={isPay}
            onClick={handleConfirm}
          >
            {isPay ? "支付中..." : "确认支付"}
          </button>
        </div>
      </div>
    </Modal>
  )
}

// apps/web/src/views/Course/components/Pay.vue
<template>
  <Teleport to="body">
    <Transition name="pay-fade">
      <div v-if="modelValue" class="fixed inset-0 z-50 flex items-center justify-center p-4">
        <!-- 遮罩 -->
        <div class="absolute inset-0 bg-zinc-900/50 backdrop-blur-sm" aria-hidden="true" />

        <!-- 弹框 -->
        <div
          class="relative w-full max-w-md rounded-2xl bg-white shadow-xl shadow-indigo-500/10 border border-zinc-100 overflow-hidden"
          role="dialog"
          aria-modal="true"
          aria-labelledby="pay-dialog-title"
        >
          <!-- 标题 -->
          <div class="px-6 pt-6 pb-4 border-b border-zinc-100">
            <h2 id="pay-dialog-title" class="text-lg font-semibold text-zinc-900">确认支付</h2>
            <p class="mt-1 text-sm text-zinc-500">请核对课程信息后完成支付</p>
          </div>
          <!-- 课程信息（有 course 时展示） -->
          <div v-if="course" class="p-6 space-y-4">
            <div class="flex gap-4 rounded-xl bg-zinc-50/80 p-4">
              <div class="w-20 h-20 shrink-0 rounded-lg overflow-hidden bg-zinc-200">
                <img
                  :src="imageSrc(course.url)"
                  :alt="course.name"
                  class="w-full h-full object-cover"
                />
              </div>
              <div class="min-w-0 flex-1">
                <h3 class="text-sm font-medium text-zinc-900 line-clamp-2">{{ course.name }}</h3>
                <p class="mt-1 text-xs text-zinc-500">讲师 {{ course.teacher }}</p>
              </div>
            </div>
            <div
              class="flex items-center justify-between rounded-xl border border-zinc-100 bg-indigo-50/50 px-4 py-3"
            >
              <span class="text-sm text-zinc-600">支付金额</span>
              <span class="text-xl font-bold text-indigo-600">¥{{ course.price }}</span>
            </div>
            <!-- 支付剩余时间倒计时（创建订单后显示） -->
            <div
              v-if="timeExpire > 0"
              class="flex flex-col items-center rounded-xl border border-amber-100 bg-amber-50/50 px-4 py-3"
            >
              <el-countdown
                title="支付剩余时间"
                format="HH:mm:ss"
                :value="timeExpire"
                @finish="tips"
              />
            </div>
          </div>

          <!-- 无数据时的占位 -->
          <div v-else class="p-6 text-center text-sm text-zinc-400">暂无课程信息</div>

          <!-- 底部按钮 -->
          <div class="flex gap-3 px-6 pb-6 pt-2">
            <button
              type="button"
              class="flex-1 py-2.5 rounded-xl text-sm font-medium text-zinc-600 border border-zinc-200 bg-white hover:bg-zinc-50 transition-colors"
              @click="close"
            >
              取消
            </button>
            <button
              type="button"
              class="flex-1 py-2.5 rounded-xl text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-500 transition-colors shadow-sm disabled:opacity-50 disabled:cursor-not-allowed"
              :disabled="isPay"
              @click="onConfirm"
            >
              {{ isPay ? '支付中...' : '确认支付' }}
            </button>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<script setup lang="ts">
  import { ref, watch } from 'vue'
  import type { Course } from '@en/common/course'
  import { ElMessage } from 'element-plus'
  import { uploadUrl } from '@/apis'
  import type { CreatePayDto } from '@en/common/pay'
  import { createPay } from '@/apis/pay'
  import { useSocket } from '@/hooks/useSocket'
  const { getSocket } = useSocket()
  const modelValue = defineModel<boolean>('modelValue', { required: true })
  const props = defineProps<{
    course: Course | null
  }>()
  const isPay = ref(false) //是否支付中
  const timeExpire = ref(0) //支付剩余时间

  watch(modelValue, newVal => {
    const socket = getSocket()
    if (newVal) {
      socket?.on('paymentSuccess', () => {
        ElMessage.success({
          message: '支付成功',
          duration: 10000, //10秒后自动关闭
        })
        close()
      })
    } else {
      socket?.off('paymentSuccess')
    }
  })

  //图片地址
  const imageSrc = (url: string) => {
    return uploadUrl + url
  }

  //倒计时结束说明超时了，提示用户重新支付
  const tips = () => {
    ElMessage.error('支付超时，请重新支付')
    timeExpire.value = 0
    isPay.value = false
  }

  //关闭弹框
  const close = () => {
    modelValue.value = false //关闭弹框
    timeExpire.value = 0 //重置倒计时
    isPay.value = false //重置支付状态
  }

  //点击确认支付
  const onConfirm = async () => {
    const body: CreatePayDto = {
      subject: props.course?.name || '',
      body: props.course?.description || '',
      total_amount: props.course?.price || '',
      courseId: props.course?.id || '',
    }
    const res = await createPay(body)
    if (res.code === 200) {
      isPay.value = true //设置支付中
      window.open(res.data.payUrl, '_blank') //打开支付页面
      timeExpire.value = res.data.timeExpire //设置倒计时
    } else {
      ElMessage.error(res.message) //提示错误
      isPay.value = false //重置支付状态
    }
  }
</script>

<style scoped>
  .pay-fade-enter-active,
  .pay-fade-leave-active {
    transition: opacity 0.2s ease;
  }

  .pay-fade-enter-from,
  .pay-fade-leave-to {
    opacity: 0;
  }
</style>
