// apps/web/src/views/Chat/index.vue
<template>
  <div class="w-[1200px] mx-auto flex mt-10">
    <Conversations @onGetRole="getRole" />
    <Bubble :list="list" @onSendMessage="sendMessage" />
  </div>
</template>
<script setup lang="ts">
  import Conversations from './components/Conversations.vue'
  import Bubble from './components/Bubble.vue'
  import { useUserStore } from '@/stores/user'
  import { ref } from 'vue'
  import { getChatHistory } from '@/apis/chat'
  import type { ChatRoleType, ChatMessageList, ChatDto, ChatMessage } from '@en/common/chat'
  import { sse, CHAT_URL } from '@/apis/sse'
  const userStore = useUserStore()
  const list = ref<ChatMessageList>([]) //存储历史记录的数组
  const userId = userStore.user?.id
  const role = ref<ChatRoleType>('normal') //存储角色
  const getRole = async (params: ChatRoleType) => {
    role.value = params
    const res = await getChatHistory(userId!, params) //获取历史记录
    list.value = res.data //存储历史记录
  }
  const sendMessage = (message: string, deepThink: boolean, webSearch: boolean) => {
    list.value.push({ role: 'human', content: message, type: 'chat' }) //添加用户的消息
    list.value.push({ role: 'ai', content: '', reasoning: '', type: 'chat' }) //添加AI的消息
    sse<ChatMessage, ChatDto>(
      CHAT_URL,
      'POST',
      { role: role.value, content: message, userId: userId!, deepThink, webSearch },
      data => {
        if (data.type === 'reasoning') {
          const last = list.value[list.value.length - 1]
          if (last && last.reasoning !== undefined) {
            last.reasoning += data.content
          }
        }
        if (data.type === 'chat') {
          const last = list.value[list.value.length - 1]
          if (last && last.content !== undefined) {
            last.content += data.content
          }
        }
      }
    )
  }
</script>

// apps/react-web/src/views/Chat/index.tsx
import { useState } from "react"
import { useUserStore } from "@/stores/user"
import { sse, CHAT_URL } from "@/apis/sse"
import { getChatHistory } from "@/apis/chat"
import type { ChatRoleType, ChatMessageList, ChatDto, ChatMessage } from "@en/common/chat"
import Conversations from "./components/Conversations"
import Bubble from "./components/Bubble"

export function Chat() {
  const user = useUserStore((s) => s.user)
  const [list, setList] = useState<ChatMessageList>([])
  const [role, setRole] = useState<ChatRoleType>("normal")

  const getRole = async (params: ChatRoleType) => {
    setRole(params)
    if (user?.id) {
      const res = await getChatHistory(user.id, params)
      setList(res.data)
    }
  }

  const sendMessage = (message: string, deepThink: boolean, webSearch: boolean) => {
    if (!user?.id) return

    // 添加用户消息
    const userMsg: ChatMessage = { role: "human", content: message, type: "chat" }
    // 添加 AI 占位消息
    const aiMsg: ChatMessage = { role: "ai", content: "", reasoning: "", type: "chat" }
    setList((prev) => [...prev, userMsg, aiMsg])

    sse<ChatMessage, ChatDto>(
      CHAT_URL,
      "POST",
      { role, content: message, userId: user.id, deepThink, webSearch },
      (data) => {
        setList((prev) => {
          const newList = [...prev]
          const last = newList[newList.length - 1]
          if (!last) return prev
          if (data.type === "reasoning" && last.reasoning !== undefined) {
            last.reasoning += data.content
          }
          if (data.type === "chat" && last.content !== undefined) {
            last.content += data.content
          }
          return newList
        })
      }
    )
  }

  return (
    <div className="flex h-[calc(100vh-4rem)] max-w-6xl mx-auto mt-6">
      <Conversations onGetRole={getRole} />
      <Bubble list={list} onSendMessage={sendMessage} />
    </div>
  )
}
