// apps/web/src/layout/Profile/index.vue
<template>
  <section class="w-80 rounded-2xl bg-white overflow-hidden" aria-label="用户资料卡">
    <!-- 头像 + 信息 -->
    <div class="flex items-center gap-3 px-4 pt-4 pb-3">
      <img
        class="w-11 h-11 rounded-full border border-border object-cover shrink-0"
        :src="avatar"
        loading="lazy"
      />
      <div class="min-w-0 flex-1">
        <div class="text-sm font-semibold text-text-primary truncate" :title="displayName">
          {{ displayName }}
        </div>
        <div v-if="bio" class="text-xs text-text-tertiary truncate mt-0.5" :title="bio">
          {{ bio }}
        </div>
        <div v-if="!isLoggedIn" class="text-xs text-text-tertiary mt-1">
          登录后可同步词库进度与打卡数据
        </div>
      </div>
    </div>

    <!-- 统计数据 -->
    <div v-if="isLoggedIn" class="grid grid-cols-2 gap-2 px-4 pb-3">
      <div class="rounded-xl border border-border bg-surface px-3 py-2.5">
        <div class="text-xs text-text-tertiary">单词数量</div>
        <div class="mt-1 text-lg font-bold text-text-primary">
          {{ userStore?.getUser?.wordNumber ?? 0 }}
        </div>
      </div>
      <div class="rounded-xl border border-accent-400/20 bg-accent-50 px-3 py-2.5">
        <div class="text-xs text-text-tertiary">打卡天数</div>
        <div class="mt-1 text-lg font-bold text-text-primary">
          {{ userStore?.getUser?.dayNumber ?? 0 }}
        </div>
      </div>
    </div>

    <!-- 操作按钮 -->
    <div class="flex gap-2 border-t border-border px-4 py-3">
      <button
        v-if="!isLoggedIn"
        class="btn-primary flex-1 h-10 text-sm cursor-pointer"
        type="button"
        @click="loginHandle"
      >
        去登录
      </button>
      <template v-else>
        <button
          class="btn-ghost flex-1 h-10 text-sm border border-border cursor-pointer"
          type="button"
          @click="gotoPath('/setting/index')"
        >
          个人资料
        </button>
        <button
          class="btn-danger flex-1 h-10 text-sm border border-red-200 cursor-pointer"
          type="button"
          @click="logoutHandle"
        >
          退出登录
        </button>
      </template>
    </div>
  </section>
</template>

<script setup lang="ts">
  import { computed } from 'vue' //引入计算属性
  import { useRouter } from 'vue-router' //引入路由
  import { useUserStore } from '@/stores/user' //引入用户信息
  import { useAvatar } from '@/hooks/useAvatar'
  import { useLogin } from '@/hooks/useLogin'
  import { ElMessageBox } from 'element-plus'

  const { login, logout } = useLogin()
  const { avatar } = useAvatar()
  const userStore = useUserStore() //初始化用户信息
  const isLoggedIn = computed(() => !!userStore.getUser) //是否登录
  const router = useRouter() //初始化路由
  const bio = computed(() => userStore.getUser?.bio ?? '') //签名
  const displayName = computed(() => userStore.getUser?.name ?? '游客') //用户名
  //跳转页面
  const gotoPath = (path: string) => {
    router.push(path)
  }
  //去登录
  const loginHandle = () => {
    login()
  }
  //退出登录
  const logoutHandle = () => {
    ElMessageBox.confirm('确定退出登录吗？', '提示', {
      confirmButtonText: '确定',
      cancelButtonText: '取消',
      type: 'warning',
    }).then(() => {
      logout()
    })
  }
</script>

// apps/react-web/src/layout/Profile/index.tsx
import { useNavigate } from "react-router"
import { Modal } from "antd"
import { useUserStore } from "@/stores/user"
import { useAvatar } from "@/hooks/useAvatar"
import { useLogin } from "@/hooks/useLogin"

export default function AppProfile() {
  const navigate = useNavigate()
  const { avatar } = useAvatar()
  const { login, logout } = useLogin()
  const user = useUserStore((s) => s.user)
  const isLoggedIn = !!user
  const displayName = user?.name ?? "游客"
  const bio = user?.bio ?? ""

  const gotoPath = (path: string) => navigate(path)

  const logoutHandle = () => {
    Modal.confirm({
      title: "提示",
      content: "确定退出登录吗？",
      okText: "确定",
      cancelText: "取消",
      onOk: () => logout(),
    })
  }

  return (
    <section className="w-80 rounded-2xl bg-white overflow-hidden">
      {/* 头像 + 信息 */}
      <div className="flex items-center gap-3 px-4 pt-4 pb-3">
        <img
          className="w-11 h-11 rounded-full border border-gray-200 object-cover shrink-0"
          src={avatar}
          alt={displayName}
        />
        <div className="min-w-0 flex-1">
          <div className="text-sm font-semibold text-gray-800 truncate" title={displayName}>
            {displayName}
          </div>
          {bio && (
            <div className="text-xs text-gray-400 truncate mt-0.5" title={bio}>
              {bio}
            </div>
          )}
          {!isLoggedIn && (
            <div className="text-xs text-gray-400 mt-1">
              登录后可同步词库进度与打卡数据
            </div>
          )}
        </div>
      </div>

      {/* 统计数据 */}
      {isLoggedIn && (
        <div className="grid grid-cols-2 gap-2 px-4 pb-3">
          <div className="rounded-xl border border-gray-200 bg-gray-50 px-3 py-2.5">
            <div className="text-xs text-gray-400">单词数量</div>
            <div className="mt-1 text-lg font-bold text-gray-800">
              {user?.wordNumber ?? 0}
            </div>
          </div>
          <div className="rounded-xl border border-orange-200 bg-orange-50 px-3 py-2.5">
            <div className="text-xs text-gray-400">打卡天数</div>
            <div className="mt-1 text-lg font-bold text-gray-800">
              {user?.dayNumber ?? 0}
            </div>
          </div>
        </div>
      )}

      {/* 操作按钮 */}
      <div className="flex gap-2 border-t border-gray-200 px-4 py-3">
        {!isLoggedIn ? (
          <button
            className="flex-1 h-10 text-sm bg-blue-600 text-white rounded-lg font-medium cursor-pointer hover:bg-blue-700"
            type="button"
            onClick={() => login()}
          >
            去登录
          </button>
        ) : (
          <>
            <button
              className="flex-1 h-10 text-sm border border-gray-200 rounded-lg cursor-pointer hover:bg-gray-50"
              type="button"
              onClick={() => gotoPath("/setting")}
            >
              个人资料
            </button>
            <button
              className="flex-1 h-10 text-sm border border-red-200 text-red-500 rounded-lg cursor-pointer hover:bg-red-50"
              type="button"
              onClick={logoutHandle}
            >
              退出登录
            </button>
          </>
        )}
      </div>
    </section>
  )
}
