// apps/react-web/src/components/Search/index.tsx
import { useState, useEffect, useCallback } from "react"
import { Input, App } from "antd"
import { SearchOutlined } from "@ant-design/icons"
import { getWordBookList } from "@/apis/word-book"
import type { Word } from "@en/common/word"

export default function Search() {
  const [isShow, setIsShow] = useState(false)
  const [search, setSearch] = useState("")
  const [wordList, setWordList] = useState<Word[]>([])
  const { message } = App.useApp()

  const getList = useCallback(async (keyword: string) => {
    const res = await getWordBookList({ word: keyword, page: 1, pageSize: 20 })
    if (res.success) {
      setWordList(res.data.list)
    }
  }, [])

  // 防抖搜索
  useEffect(() => {
    if (!isShow) return
    const timer = setTimeout(() => {
      if (search) getList(search)
    }, 500)
    return () => clearTimeout(timer)
  }, [search, isShow, getList])

  // 全局快捷键
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === "f" && e.ctrlKey) {
        e.preventDefault()
        setIsShow(true)
        document.body.style.overflow = "hidden"
      }
      if (e.key === "Escape") {
        setIsShow(false)
        setSearch("")
        document.body.style.overflow = "auto"
      }
    }
    window.addEventListener("keydown", handler)
    return () => window.removeEventListener("keydown", handler)
  }, [])

  const copyWord = (word: string) => {
    navigator.clipboard.writeText(word)
      .then(() => message.success("复制成功"))
      .catch(() => message.error("复制失败"))
  }

  if (!isShow) return null

  return (
    <>
      <div className="fixed inset-0 z-40 bg-black/30 blur-sm" onClick={() => setIsShow(false)} />
      <div className="fixed inset-0 z-50 p-30 pt-20">
        <div
          className={`flex items-center gap-2 shadow-lg w-1/2 mx-auto p-3 bg-white ${wordList.length > 0 ? "rounded-t-xl" : "rounded-xl"}`}
        >
          <SearchOutlined className="text-lg text-gray-400" />
          <Input
            autoFocus
            placeholder="搜索"
            variant="borderless"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
        {wordList.length > 0 && (
          <div className="w-1/2 mx-auto max-h-[500px] border-t border-gray-200 overflow-y-auto">
            {wordList.map((item) => (
              <div
                key={item.id}
                onClick={() => copyWord(item.word)}
                className="bg-white hover:bg-blue-50 text-gray-800 p-4 cursor-pointer shadow-sm hover:shadow-md"
              >
                <div className="text-sm font-semibold text-blue-600 mb-1">{item.word}</div>
                <div
                  className="text-sm text-gray-700 line-clamp-2"
                  dangerouslySetInnerHTML={{ __html: item.translation || "" }}
                />
              </div>
            ))}
          </div>
        )}
      </div>
    </>
  )
}

// apps/web/src/components/Search/index.vue
<template>
  <div v-if="isShow" class="fixed inset-0 w-full h-full z-40 bg-black opacity-30 blur-sm" />
  <Transition name="fade">
    <div v-if="isShow" class="fixed inset-0 shadow-lg z-50 p-30 pt-20">
      <div
        :class="wordList.length > 0 ? 'rounded-tr-[10px] rounded-tl-[10px]' : 'rounded-[10px]'"
        class="flex items-center gap-2 shadow-lg w-1/2 mx-auto p-3 bg-white"
      >
        <el-icon size="20">
          <Search />
        </el-icon>
        <input
          v-focus
          placeholder="搜索"
          type="text"
          v-model="search"
          class="w-full h-full text-sm border-none rounded-lg p-2 focus:outline-none"
        />
      </div>
      <div
        v-if="wordList.length > 0"
        class="w-1/2 mx-auto max-h-125 border-t border-gray-200 overflow-y-auto"
      >
        <div
          @click="copyWord(item.word)"
          v-for="item in wordList"
          :key="item.id"
          class="bg-white hover:bg-blue-50 text-gray-800 p-4 cursor-pointer shadow-sm hover:shadow-md"
        >
          <div class="text-sm font-semibold text-blue-600 mb-1">{{ item.word }}</div>
          <div
            v-html="item.translation"
            class="text-sm text-gray-700 mb-1 overflow-hidden line-clamp-2"
          />
        </div>
      </div>
    </div>
  </Transition>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Search } from '@element-plus/icons-vue'
import type { Word } from '@en/common/word'
import { getWordBookList } from '@/apis/word-book'
import { ElMessage } from 'element-plus'
import { useDebouncedRef } from '@/hooks/useDebouncedRef'
const wordList = ref<Word[]>([]) //搜索结果
const isShow = ref(false) //用来展示弹框的显示和隐藏的

// let timer: ReturnType<typeof setTimeout> | null = null
// const search = customRef((track, trigger) => {
//   let value = '' //默认值
//   return {
//     get() {
//       track() //告诉vue追踪value的值
//       return value
//     },
//     set(newValue: string) {
//       value = newValue
//       if (timer) {
//         clearTimeout(timer)
//       }
//       timer = setTimeout(() => {
//         console.log(value)
//         if (isShow.value) getList()
//         trigger() //告诉vue触发value的值，从而触发依赖
//       }, 500)
//     },
//   }
// }) //搜索的一个值
const search = useDebouncedRef('', 500, (val) => {
  if (isShow.value) getList()
})

const getList = async () => {
  const res = await getWordBookList({ word: search.value, page: 1, pageSize: 20 })
  if (res.success) {
    wordList.value = res.data.list
  }
}
const copyWord = (word: string) => {
  try {
    navigator.clipboard.writeText(word) //localhost  / https
    ElMessage.success('复制成功')
  } catch (error) {
    ElMessage.error('复制失败')
  }
}
window.addEventListener('keydown', (e: KeyboardEvent) => {
  if (e.key === 'f' && e.ctrlKey) {
    e.preventDefault()
    isShow.value = true
    document.body.style.overflow = 'hidden'
  }
  if (e.key === 'Escape') {
    isShow.value = false
    search.value = ''
    document.body.style.overflow = 'auto'
  }
})
</script>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: all 0.3s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
  transform: scale(0.5);
}

.fade-enter-to,
.fade-leave-from {
  opacity: 1;
  transform: scale(1);
}
</style>
